from __future__ import annotations

import json
from pathlib import Path
import unittest

from scripts.run_sst_spine_vertical import (
    validate_carry_hot_result,
    validate_fallback_result,
    validate_full_compute_result,
    validate_multiround_sssp_result,
    validate_protocol_window_result,
    validate_result,
)


ROOT = Path(__file__).resolve().parents[1]


class SstSpineVerticalValidationTests(unittest.TestCase):
    def test_matching_architecture_and_dram_counts_pass(self) -> None:
        result = {
            "success": True,
            "mode": "spine_vertical",
            "spine_axi_profile": "hls_split_9c08763",
            "correctness_mismatches": 0,
            "frontier_mismatches": 0,
            "next_active": 10,
            "maintenance_scan_passes": 20,
            "maintenance_edge_visits": 200,
            "maintenance_sorted_bytes": 3_200,
            "maintenance_sorted_payload_read_bytes": 3_200,
            "maintenance_sorted_read_beats": 200,
            "maintenance_sorted_axi_read_beats_streamed": 200,
            "maintenance_max_scan_buffered_edges": 10,
            "maintenance_dirty_validate_visits": 10,
            "maintenance_dirty_mark_visits": 10,
            "maintenance_hot_cold_count_visits": 10,
            "maintenance_family_precount_visits": 160,
            "maintenance_l0_write_visits": 10,
            "reader_tiles": 5,
            "reader_edges": 10,
            "reader_graph_bytes": 184,
            "maintenance_graph_index_payload_write_bytes": 64,
            "maintenance_graph_payload_write_bytes": 80,
            "reader_graph_index_payload_bytes": 24,
            "reader_graph_payload_bytes": 160,
            "reader_construction_payload_bytes": 80,
            "reader_replay_payload_bytes": 80,
            "reader_graph_index_bitmap_misses": 0,
            "reader_range_path": 1,
            "reader_range_error": 0,
            "reader_range_fallback_reason": 0,
            "reader_range_tasks": 5,
            "reader_range_row_lookups": 1,
            "reader_range_active_records": 1,
            "reader_range_family_probes": 16,
            "reader_range_family_skips": 0,
            "reader_range_level_checks": 176,
            "reader_range_construction_payloads": 10,
            "reader_range_replay_payloads": 10,
            "reader_range_clear_cycles": 256,
            "reader_range_prefix_cycles": 256,
            "reader_range_scatter_cycles": 5,
            "reader_range_verify_cycles": 256,
            "reader_metadata_bytes": 2_928,
            "reader_dirty_list_bytes": 16,
            "reader_dirty_bitmap_bytes": 16,
            "reader_active_bin_bytes": 0,
            "reader_source_requests": 1,
            "reader_source_responses": 1,
            "reader_source_windows": 1,
            "reader_protocol_markers": 3,
            "reader_protocol_acks": 1,
            "reader_protocol_status": 0,
            "reader_dirty_status": 0,
            "reader_metadata_write_bytes": 16,
            "reader_result_write_bytes": 64,
            "reader_diagnostic_words": 10,
            "reader_done_words": 1,
            "reader_done_overflow": 0,
            "compute_protocol_markers": 3,
            "compute_protocol_acks": 1,
            "compute_protocol_status": 0,
            "compute_diagnostic_words": 10,
            "compute_done_words": 1,
            "compute_done_overflow": 0,
            "compute_range_path": 1,
            "compute_range_fallback_reason": 0,
            "compute_range_error": 0,
            "compute_range_tasks": 5,
            "compute_range_row_lookups": 1,
            "compute_range_construction_payloads": 10,
            "compute_range_replay_payloads": 10,
            "compute_range_active_records": 1,
            "compute_range_family_probes": 16,
            "compute_range_family_skips": 0,
            "compute_dirty_count": 1,
            "compute_dirty_generation": 1,
            "reader_page_epoch_misses": 0,
            "reader_occupied_levels": 1,
            "compute_fast_tiles": 5,
            "compute_full_tiles": 0,
            "compute_processed_edges": 10,
            "edge_axis_transfers": 35,
            "edge_axis_max_occupancy": 15,
            "value_axis_transfers": 2,
            "backend_requests": 100,
        }
        dram = {"dram_reads": 60, "dram_writes": 40, "dram_channels": 32}
        self.assertEqual(validate_result(result, dram, channels=32), [])

    def test_dram_request_drop_is_rejected(self) -> None:
        result = {
            "success": True,
            "mode": "spine_vertical",
            "correctness_mismatches": 0,
            "frontier_mismatches": 0,
            "next_active": 10,
            "maintenance_scan_passes": 19,
            "maintenance_edge_visits": 190,
            "maintenance_sorted_bytes": 3_040,
            "reader_tiles": 5,
            "reader_edges": 10,
            "reader_graph_bytes": 112,
            "reader_metadata_bytes": 2_928,
            "reader_occupied_levels": 1,
            "compute_fast_tiles": 5,
            "compute_full_tiles": 0,
            "compute_processed_edges": 10,
            "edge_axis_transfers": 22,
            "edge_axis_max_occupancy": 15,
            "backend_requests": 100,
        }
        dram = {"dram_reads": 59, "dram_writes": 40, "dram_channels": 32}
        self.assertIn(
            "dram_matches_backend", validate_result(result, dram, channels=32)
        )

    def test_frontier_mismatch_is_rejected(self) -> None:
        result = {
            "success": True,
            "mode": "spine_vertical",
            "correctness_mismatches": 0,
            "frontier_mismatches": 1,
            "next_active": 10,
            "maintenance_scan_passes": 19,
            "maintenance_edge_visits": 190,
            "maintenance_sorted_bytes": 3_040,
            "reader_tiles": 5,
            "reader_edges": 10,
            "reader_graph_bytes": 112,
            "reader_metadata_bytes": 2_928,
            "reader_occupied_levels": 1,
            "compute_fast_tiles": 5,
            "compute_full_tiles": 0,
            "compute_processed_edges": 10,
            "edge_axis_transfers": 22,
            "edge_axis_max_occupancy": 15,
            "backend_requests": 100,
        }
        dram = {"dram_reads": 60, "dram_writes": 40, "dram_channels": 32}
        self.assertIn(
            "frontier_correctness", validate_result(result, dram, channels=32)
        )

    def test_carry_hot_structure_and_memory_closure_pass(self) -> None:
        result = {
            "success": True,
            "mode": "spine_vertical",
            "spine_axi_profile": "hls_split_9c08763",
            "correctness_mismatches": 0,
            "frontier_mismatches": 0,
            "next_active": 3,
            "input_edges": 2,
            "preload_edges": 1,
            "maintenance_target_level": 1,
            "maintenance_hot_target_level": 0,
            "maintenance_cold_input_edges": 1,
            "maintenance_hot_input_edges": 1,
            "maintenance_scan_passes": 36,
            "maintenance_edge_visits": 72,
            "maintenance_sorted_bytes": 1_152,
            "maintenance_sorted_payload_read_bytes": 1_152,
            "maintenance_sorted_read_beats": 72,
            "maintenance_sorted_axi_read_beats_streamed": 72,
            "maintenance_max_scan_buffered_edges": 2,
            "maintenance_dirty_validate_visits": 2,
            "maintenance_dirty_mark_visits": 2,
            "maintenance_hot_cold_count_visits": 2,
            "maintenance_family_precount_visits": 64,
            "maintenance_l0_write_visits": 2,
            "maintenance_carry_payload_reads": 1,
            "maintenance_carry_payload_read_bytes": 8,
            "maintenance_carry_merge_inputs": 2,
            "maintenance_carry_outputs": 2,
            "reader_tiles": 1,
            "reader_edges": 3,
            "reader_graph_bytes": 96,
            "maintenance_graph_index_payload_write_bytes": 128,
            "maintenance_graph_payload_write_bytes": 24,
            "reader_graph_index_payload_bytes": 48,
            "reader_graph_payload_bytes": 48,
            "reader_construction_payload_bytes": 24,
            "reader_replay_payload_bytes": 24,
            "reader_graph_index_bitmap_misses": 0,
            "reader_range_path": 1,
            "reader_range_error": 0,
            "reader_range_fallback_reason": 0,
            "reader_range_tasks": 2,
            "reader_range_row_lookups": 2,
            "reader_range_active_records": 1,
            "reader_range_family_probes": 32,
            "reader_range_family_skips": 0,
            "reader_range_level_checks": 352,
            "reader_range_construction_payloads": 3,
            "reader_range_replay_payloads": 3,
            "reader_metadata_bytes": 3_000,
            "reader_dirty_list_bytes": 16,
            "reader_dirty_bitmap_bytes": 16,
            "reader_active_bin_bytes": 0,
            "reader_source_requests": 1,
            "reader_source_responses": 1,
            "reader_source_windows": 1,
            "reader_protocol_markers": 3,
            "reader_protocol_acks": 1,
            "reader_protocol_status": 0,
            "reader_dirty_status": 0,
            "reader_metadata_write_bytes": 16,
            "reader_result_write_bytes": 64,
            "reader_diagnostic_words": 10,
            "reader_done_words": 1,
            "reader_done_overflow": 0,
            "compute_protocol_markers": 3,
            "compute_protocol_acks": 1,
            "compute_protocol_status": 0,
            "compute_diagnostic_words": 10,
            "compute_done_words": 1,
            "compute_done_overflow": 0,
            "compute_range_path": 1,
            "compute_range_fallback_reason": 0,
            "compute_range_error": 0,
            "compute_range_tasks": 2,
            "compute_range_row_lookups": 2,
            "compute_range_construction_payloads": 3,
            "compute_range_replay_payloads": 3,
            "compute_range_active_records": 1,
            "compute_range_family_probes": 32,
            "compute_range_family_skips": 0,
            "compute_dirty_count": 1,
            "compute_dirty_generation": 1,
            "reader_page_epoch_misses": 0,
            "reader_occupied_levels": 2,
            "reader_cold_edges": 2,
            "reader_hot_edges": 1,
            "compute_fast_tiles": 1,
            "compute_full_tiles": 0,
            "compute_processed_edges": 3,
            "edge_axis_transfers": 20,
            "edge_axis_max_occupancy": 5,
            "value_axis_transfers": 2,
            "backend_requests": 100,
        }
        dram = {"dram_reads": 60, "dram_writes": 40, "dram_channels": 32}
        self.assertEqual(validate_carry_hot_result(result, dram, channels=32), [])

    def test_real_full_tile_compute_structure_passes(self) -> None:
        result = {
            "success": True,
            "mode": "spine_compute",
            "correctness_mismatches": 0,
            "frontier_mismatches": 0,
            "expected_frontier": 40_000,
            "next_active": 40_000,
            "input_edges": 64_658,
            "compute_fast_tiles": 11,
            "compute_full_tiles": 1,
            "compute_processed_edges": 64_658,
            "compute_gathered_words": 14_676,
            "compute_swept_words": 131_072,
            "compute_full_buffer_replay_edges": 4096,
            "compute_full_overflow_edges": 1,
            "compute_full_stream_edges": 45_885,
            "compute_vertex_read_bytes": 320_848,
            "compute_vertex_payload_read_bytes": 320_848,
            "compute_vertex_write_bytes": 303_192,
            "compute_vertex_payload_write_bytes": 303_192,
            "edge_axis_transfers": 64_683,
            "edge_axis_max_occupancy": 32,
            "edge_axis_push_stalls": 10,
            "backend_requests": 100,
        }
        dram = {"dram_reads": 60, "dram_writes": 40, "dram_channels": 32}
        self.assertEqual(validate_full_compute_result(result, dram, channels=32), [])

    def test_real_full_tile_without_axis_backpressure_is_rejected(self) -> None:
        result = {
            "success": True,
            "mode": "spine_compute",
            "correctness_mismatches": 0,
            "frontier_mismatches": 0,
            "expected_frontier": 40_000,
            "next_active": 40_000,
            "input_edges": 64_658,
            "compute_fast_tiles": 11,
            "compute_full_tiles": 1,
            "compute_processed_edges": 64_658,
            "compute_gathered_words": 14_676,
            "compute_swept_words": 131_072,
            "compute_full_buffer_replay_edges": 4096,
            "compute_full_overflow_edges": 1,
            "compute_full_stream_edges": 45_885,
            "edge_axis_transfers": 64_683,
            "edge_axis_max_occupancy": 32,
            "edge_axis_push_stalls": 0,
            "backend_requests": 100,
        }
        dram = {"dram_reads": 60, "dram_writes": 40, "dram_channels": 32}
        self.assertIn(
            "axis_backpressure",
            validate_full_compute_result(result, dram, channels=32),
        )

    def test_multiround_weighted_sssp_structure_passes(self) -> None:
        result = {
            "success": True,
            "mode": "spine_sssp",
            "spine_axi_profile": "hls_split_9c08763",
            "converged": True,
            "correctness_mismatches": 0,
            "frontier_mismatches": 0,
            "input_edges": 8,
            "rounds": 6,
            "final_values": [0, 3, 2, 7, 8, 10],
            "frontier_in_sizes": [1, 3, 2, 2, 2, 1],
            "frontier_out_sizes": [3, 2, 2, 2, 1, 0],
            "processed_edges_per_round": [8, 3, 2, 2, 1, 0],
            "maintenance_scan_passes": 20,
            "maintenance_edge_visits": 160,
            "maintenance_sorted_bytes": 2_560,
            "maintenance_sorted_payload_read_bytes": 2_560,
            "maintenance_sorted_read_beats": 160,
            "maintenance_sorted_axi_read_beats_streamed": 160,
            "maintenance_max_scan_buffered_edges": 8,
            "maintenance_dirty_validate_visits": 8,
            "maintenance_dirty_mark_visits": 8,
            "maintenance_hot_cold_count_visits": 8,
            "maintenance_family_precount_visits": 128,
            "maintenance_l0_write_visits": 8,
            "round_cycles": [10, 11, 12, 13, 14, 15],
            "edge_axis_max_occupancy_per_round": [5, 6, 5, 5, 4, 2],
            "edge_axis_push_stalls_per_round": [0, 1, 0, 0, 0, 0],
            "fast_tiles_per_round": [1, 1, 1, 1, 1, 0],
            "full_tiles_per_round": [0, 0, 0, 0, 0, 0],
            "reader_metadata_bytes_per_round": [2960, 3232, 3232, 3232, 3224, 3216],
            "reader_metadata_write_bytes_per_round": [16, 16, 16, 16, 16, 16],
            "reader_result_write_bytes_per_round": [64, 64, 64, 64, 64, 64],
            "reader_source_sizes_per_round": [5, 2, 2, 2, 1, 0],
            "reader_source_requests_per_round": [5, 0, 0, 0, 0, 0],
            "reader_source_responses_per_round": [5, 0, 0, 0, 0, 0],
            "reader_source_windows_per_round": [1, 0, 0, 0, 0, 0],
            "reader_protocol_markers_per_round": [3, 0, 0, 0, 0, 0],
            "reader_protocol_acks_per_round": [1, 0, 0, 0, 0, 0],
            "reader_protocol_status_per_round": [0, 0, 0, 0, 0, 0],
            "reader_dirty_status_per_round": [0, 0, 0, 0, 0, 0],
            "reader_dirty_counts_per_round": [5, 0, 0, 0, 0, 0],
            "reader_dirty_generations_per_round": [1, 2, 2, 2, 2, 2],
            "reader_ack_eligible_per_round": [1, 0, 0, 0, 0, 0],
            "reader_host_coverage_match_per_round": [0, 0, 0, 0, 0, 0],
            "compute_protocol_status_per_round": [0, 0, 0, 0, 0, 0],
            "reader_dirty_list_bytes_per_round": [80, 0, 0, 0, 0, 0],
            "reader_dirty_bitmap_bytes_per_round": [80, 0, 0, 0, 0, 0],
            "reader_active_bin_bytes_per_round": [0, 64, 64, 64, 32, 0],
            "reader_epoch_misses_per_round": [0, 0, 0, 0, 0, 0],
            "edge_axis_transfers_per_round": [29, 16, 15, 15, 14, 11],
            "value_axis_transfers_per_round": [6, 0, 0, 0, 0, 0],
            "value_axis_max_occupancy_per_round": [5, 0, 0, 0, 0, 0],
            "maintenance_graph_index_payload_write_bytes": 88,
            "maintenance_graph_payload_write_bytes": 64,
            "reader_graph_index_payload_bytes_per_round": [136, 56, 64, 56, 24, 0],
            "reader_graph_payload_bytes_per_round": [128, 48, 32, 32, 16, 0],
            "reader_construction_payload_bytes_per_round": [64, 24, 16, 16, 8, 0],
            "reader_replay_payload_bytes_per_round": [64, 24, 16, 16, 8, 0],
            "reader_graph_index_bitmap_misses_per_round": [0, 0, 0, 0, 0, 0],
            "reader_range_tasks_per_round": [5, 2, 2, 2, 1, 0],
            "reader_range_row_lookups_per_round": [5, 2, 2, 2, 1, 0],
            "reader_range_level_checks_per_round": [880, 22, 22, 22, 11, 0],
            "reader_range_construction_payloads_per_round": [8, 3, 2, 2, 1, 0],
            "reader_range_replay_payloads_per_round": [8, 3, 2, 2, 1, 0],
            "reader_range_active_records_per_round": [5, 2, 2, 2, 1, 0],
            "reader_range_family_probes_per_round": [80, 2, 2, 2, 1, 0],
            "reader_range_family_skips_per_round": [0, 0, 0, 0, 0, 0],
            "reader_range_paths_per_round": [1, 1, 1, 1, 1, 1],
            "reader_range_fallback_reasons_per_round": [0, 0, 0, 0, 0, 0],
            "reader_range_errors_per_round": [0, 0, 0, 0, 0, 0],
            "reader_diagnostic_words_per_round": [10, 10, 10, 10, 10, 10],
            "reader_done_words_per_round": [1, 1, 1, 1, 1, 1],
            "reader_done_overflow_per_round": [0, 0, 0, 0, 0, 0],
            "compute_diagnostic_words_per_round": [10, 10, 10, 10, 10, 10],
            "compute_done_words_per_round": [1, 1, 1, 1, 1, 1],
            "compute_done_overflow_per_round": [0, 0, 0, 0, 0, 0],
            "compute_range_paths_per_round": [1, 1, 1, 1, 1, 1],
            "compute_range_fallback_reasons_per_round": [0, 0, 0, 0, 0, 0],
            "compute_range_errors_per_round": [0, 0, 0, 0, 0, 0],
            "compute_range_tasks_per_round": [5, 2, 2, 2, 1, 0],
            "compute_range_row_lookups_per_round": [5, 2, 2, 2, 1, 0],
            "compute_range_construction_payloads_per_round": [8, 3, 2, 2, 1, 0],
            "compute_range_replay_payloads_per_round": [8, 3, 2, 2, 1, 0],
            "compute_range_active_records_per_round": [5, 2, 2, 2, 1, 0],
            "compute_range_family_probes_per_round": [80, 2, 2, 2, 1, 0],
            "compute_range_family_skips_per_round": [0, 0, 0, 0, 0, 0],
            "compute_dirty_counts_per_round": [5, 0, 0, 0, 0, 0],
            "compute_dirty_generations_per_round": [1, 2, 2, 2, 2, 2],
            "dirty_ack_started": 1,
            "dirty_ack_status": 0,
            "dirty_ack_cycles": 10,
            "dirty_ack_captured_count": 5,
            "dirty_ack_captured_generation": 1,
            "dirty_ack_result_count": 0,
            "dirty_ack_result_generation": 2,
            "dirty_ack_candidate_write_bytes": 40,
            "dirty_ack_metadata_read_bytes": 72,
            "dirty_ack_metadata_write_bytes": 64,
            "dirty_ack_list_read_bytes": 160,
            "dirty_ack_bitmap_read_bytes": 160,
            "dirty_ack_bitmap_write_bytes": 80,
            "dirty_ack_validated_sources": 5,
            "dirty_ack_cleared_sources": 5,
            "dirty_ack_generation_advances": 1,
            "backend_requests": 100,
        }
        dram = {"dram_reads": 60, "dram_writes": 40, "dram_channels": 32}
        self.assertEqual(
            validate_multiround_sssp_result(result, dram, channels=32), []
        )

    def test_source_protocol_window_structure_passes(self) -> None:
        result = {
            "success": True,
            "mode": "spine_vertical",
            "correctness_mismatches": 0,
            "frontier_mismatches": 0,
            "input_edges": 17,
            "next_active": 1,
            "reader_source_requests": 17,
            "reader_source_responses": 17,
            "reader_source_windows": 2,
            "reader_protocol_markers": 3,
            "reader_protocol_acks": 1,
            "reader_protocol_status": 0,
            "reader_dirty_status": 0,
            "reader_metadata_write_bytes": 16,
            "reader_result_write_bytes": 64,
            "reader_diagnostic_words": 10,
            "reader_done_words": 1,
            "reader_done_overflow": 0,
            "compute_protocol_markers": 3,
            "compute_protocol_acks": 1,
            "compute_protocol_status": 0,
            "compute_diagnostic_words": 10,
            "compute_done_words": 1,
            "compute_done_overflow": 0,
            "reader_range_path": 1,
            "reader_range_fallback_reason": 0,
            "reader_range_error": 0,
            "reader_range_tasks": 17,
            "reader_range_row_lookups": 17,
            "reader_range_construction_payloads": 17,
            "reader_range_replay_payloads": 17,
            "reader_range_active_records": 17,
            "reader_range_family_probes": 272,
            "reader_range_family_skips": 0,
            "compute_range_path": 1,
            "compute_range_fallback_reason": 0,
            "compute_range_error": 0,
            "compute_range_tasks": 17,
            "compute_range_row_lookups": 17,
            "compute_range_construction_payloads": 17,
            "compute_range_replay_payloads": 17,
            "compute_range_active_records": 17,
            "compute_range_family_probes": 272,
            "compute_range_family_skips": 0,
            "compute_dirty_count": 17,
            "compute_dirty_generation": 1,
            "edge_axis_transfers": 50,
            "value_axis_transfers": 18,
            "edge_axis_max_occupancy": 13,
            "value_axis_max_occupancy": 2,
            "backend_requests": 100,
        }
        dram = {"dram_reads": 60, "dram_writes": 40, "dram_channels": 32}
        self.assertEqual(
            validate_protocol_window_result(result, dram, channels=32), []
        )

    def test_frozen_fallback_evidence_passes(self) -> None:
        cases = (
            ("sst_spine_fallback_capacity_20260724_summary.json", 2),
            ("sst_spine_fallback_payload_20260724_summary.json", 3),
        )
        for filename, reason in cases:
            with self.subTest(filename=filename):
                summary = json.loads(
                    (ROOT / "docs" / "evidence" / filename).read_text(
                        encoding="utf-8"
                    )
                )
                self.assertEqual(
                    validate_fallback_result(
                        summary, summary, channels=32, expected_reason=reason
                    ),
                    [],
                )


if __name__ == "__main__":
    unittest.main()
