from __future__ import annotations

import copy
import json
from pathlib import Path
import tempfile
import unittest

from spine_cycle_sim.evidence.fpga import (
    FpgaEvidenceError,
    analyze_fpga_manifest,
    parse_accelerator_utilization,
    parse_timing_summary,
    parse_xclbin_info,
)


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "configs/evidence/fpga_routed_native_20260725.json"

UTILIZATION = """\
| Tool Version : Vivado v.2024.1 (lin64)
| Design       : level0_wrapper
| Device       : xcu55c
| Design State : Routed
Accelerator Utilization Design Information
| Name               | LUT               | LUTAsMem         | REG               | BRAM              | URAM              | DSP               |
| Platform           | 10 [ 1.00%]       | 0 [ 0.00%]       | 20 [ 2.00%]       | 1 [ 1.00%]       | 0 [ 0.00%]       | 0 [ 0.00%]       |
| User Budget        | 1000 [100.00%]     | 100 [100.00%]    | 2000 [100.00%]    | 100 [100.00%]    | 10 [100.00%]     | 20 [100.00%]     |
|    Used Resources  | 100 [10.00%]       | 5 [ 5.00%]       | 200 [10.00%]      | 10 [10.00%]      | 2 [20.00%]       | 1 [ 5.00%]       |
|    Unused Resources| 900 [90.00%]       | 95 [95.00%]      | 1800 [90.00%]     | 90 [90.00%]      | 8 [80.00%]       | 19 [95.00%]      |
| kernel_a           | 60 [ 6.00%]        | 3 [ 3.00%]       | 120 [ 6.00%]      | 6 [ 6.00%]       | 2 [20.00%]       | 1 [ 5.00%]       |
|    kernel_a_1      | 60 [ 6.00%]        | 3 [ 3.00%]       | 120 [ 6.00%]      | 6 [ 6.00%]       | 2 [20.00%]       | 1 [ 5.00%]       |
"""

TIMING_MET = """\
| Tool Version      : Vivado v.2024.1 (lin64)
| Design            : level0_wrapper
| Device            : xcu55c-fsvh2892
| Design State      : Routed
| Design Timing Summary
    WNS(ns) TNS(ns)
    ------- -------
      0.003 0.000 0 100 0.009 0.000 0 100 0.000 0.000 0 50
All user specified timing constraints are met.
| Clock Summary
Clock Waveform(ns) Period(ns) Frequency(MHz)
  clk_kernel_00_unbuffered_net {0.000 2.500} 5.000 200.000
| Intra Clock Table
Clock WNS(ns)
  clk_kernel_00_unbuffered_net 0.087 0.000 0 80 0.010 0.000 0 80 1.800 0.000 0 30
| Inter Clock Table
"""

XCLBIN_INFO = """\
   Platform VBNV:          xilinx_u55c_gen3x16_xdma_3_202210_1
Scalable Clocks
   Name:      hbm_aclk
   Index:     0
   Type:      SYSTEM
   Frequency: 450 MHz

   Name:      DATA_CLK
   Index:     2
   Type:      DATA
   Frequency: 200 MHz

System Clocks
   Name:           ulp_ucs_aclk_kernel_00
   Type:           SCALABLE
   Default Freq:   300 MHz
   Requested Freq: 200 MHz
   Achieved Freq:  200 MHz

Generated By
"""


class FpgaEvidenceTests(unittest.TestCase):
    def test_parses_utilization_hierarchy(self) -> None:
        report = parse_accelerator_utilization(UTILIZATION)
        self.assertEqual(report["used_resources"]["lut"]["count"], 100)
        self.assertEqual(report["used_resources"]["uram"]["user_budget_pct"], 20.0)
        self.assertEqual([row["name"] for row in report["components"]], ["kernel_a"])
        self.assertEqual([row["name"] for row in report["instances"]], ["kernel_a_1"])

    def test_parses_requested_and_intra_clock_timing(self) -> None:
        report = parse_timing_summary(TIMING_MET, "clk_kernel_00_unbuffered_net")
        self.assertTrue(report["constraints_met_at_requested_clock"])
        self.assertEqual(report["design_summary"]["wns_ns"], 0.003)
        self.assertEqual(report["kernel_clock"]["requested_mhz"], 200.0)
        self.assertEqual(report["kernel_clock"]["timing"]["wns_ns"], 0.087)

    def test_parses_packaged_and_achieved_clock(self) -> None:
        report = parse_xclbin_info(XCLBIN_INFO, "ulp_ucs_aclk_kernel_00")
        self.assertEqual(report["data_clock"]["requested_mhz"], 200.0)
        self.assertEqual(report["data_clock"]["achieved_mhz"], 200.0)
        self.assertEqual(report["data_clock"]["packaged_mhz"], 200.0)

    def test_frozen_manifest_replays_exact_primary_and_negative_evidence(self) -> None:
        ledger = analyze_fpga_manifest(MANIFEST)
        by_id = {build["build_id"]: build for build in ledger["builds"]}
        spine = by_id["spine_accepted_9c08763"]
        grasu = by_id["grasu_regraph_native_a9aef06"]
        negative = by_id["spine_negative_9c08763_134"]

        self.assertEqual(spine["timing_disposition"], "packaged_after_auto_scaling")
        self.assertEqual(spine["xclbin"]["data_clock"]["packaged_mhz"], 141.0)
        self.assertEqual(spine["utilization"]["used_resources"]["lut"]["count"], 123707)
        self.assertEqual(grasu["timing_disposition"], "requested_clock_closed")
        self.assertEqual(grasu["utilization"]["used_resources"]["bram"]["count"], 248)
        self.assertEqual(negative["timing_disposition"], "timing_not_closed_at_packaged_clock")
        self.assertEqual(negative["timing"]["design_summary"]["wns_ns"], -0.252)
        self.assertEqual(ledger["status"], "PASS")

    def test_manifest_hash_mismatch_is_fatal(self) -> None:
        manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
        broken = copy.deepcopy(manifest)
        for build in broken["builds"]:
            for report in build["reports"].values():
                report["path"] = str((ROOT / report["path"]).resolve())
        broken["builds"][0]["reports"]["utilization"]["content_sha256"] = "0" * 64
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "broken.json"
            path.write_text(json.dumps(broken), encoding="utf-8")
            with self.assertRaises(FpgaEvidenceError):
                analyze_fpga_manifest(path)

    def test_missing_timing_disposition_is_rejected(self) -> None:
        with self.assertRaises(FpgaEvidenceError):
            parse_timing_summary(
                TIMING_MET.replace(
                    "All user specified timing constraints are met.", "unknown"
                ),
                "clk_kernel_00_unbuffered_net",
            )


if __name__ == "__main__":
    unittest.main()
