#!/usr/bin/env python3
"""Generate the frozen orthogonal DRAMSim3 HBM sensitivity configurations."""

from __future__ import annotations

import argparse
import configparser
import hashlib
from io import StringIO
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = (
    ROOT / "configs" / "memory" / "hbm_sensitivity_profiles_v1.json"
)


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_ini(path: Path) -> configparser.RawConfigParser:
    parser = configparser.RawConfigParser(interpolation=None)
    parser.optionxform = str
    with path.open(encoding="ascii") as stream:
        parser.read_file(stream)
    return parser


def load_manifest(path: Path) -> dict[str, object]:
    manifest = json.loads(path.read_text(encoding="ascii"))
    if manifest.get("schema_version") != 1:
        raise ValueError("unsupported HBM sensitivity manifest schema")
    baseline = manifest.get("baseline")
    profiles = manifest.get("profiles")
    if not isinstance(baseline, dict) or not isinstance(profiles, list):
        raise ValueError("HBM sensitivity manifest is incomplete")
    baseline_path = (ROOT / str(baseline["path"])).resolve()
    if sha256_file(baseline_path) != baseline.get("sha256"):
        raise ValueError("HBM sensitivity baseline hash mismatch")
    identifiers: set[str] = set()
    outputs: set[Path] = set()
    for raw_profile in profiles:
        if not isinstance(raw_profile, dict):
            raise ValueError("HBM sensitivity profile must be an object")
        profile_id = str(raw_profile.get("profile_id", ""))
        output = (ROOT / str(raw_profile.get("output", ""))).resolve()
        if not profile_id or profile_id in identifiers or output in outputs:
            raise ValueError("HBM sensitivity profiles must have unique IDs and outputs")
        if raw_profile.get("axis") not in {"latency", "bandwidth"}:
            raise ValueError(f"unsupported sensitivity axis: {profile_id}")
        if raw_profile.get("direction") not in {"low", "high"}:
            raise ValueError(f"unsupported sensitivity direction: {profile_id}")
        changes = raw_profile.get("changes")
        if not isinstance(changes, dict) or not changes:
            raise ValueError(f"sensitivity profile has no changes: {profile_id}")
        identifiers.add(profile_id)
        outputs.add(output)
    return manifest


def render_profile(
    baseline: configparser.RawConfigParser, profile: dict[str, object]
) -> str:
    rendered = configparser.RawConfigParser(interpolation=None)
    rendered.optionxform = str
    for section in baseline.sections():
        rendered.add_section(section)
        for key, value in baseline.items(section):
            rendered.set(section, key, value)
    changes = profile["changes"]
    if not isinstance(changes, dict):
        raise ValueError("profile changes must be an object")
    for dotted_key, value in changes.items():
        try:
            section, key = str(dotted_key).split(".", 1)
        except ValueError as error:
            raise ValueError(f"invalid sensitivity key: {dotted_key}") from error
        if not rendered.has_option(section, key):
            raise ValueError(f"unknown sensitivity key: {dotted_key}")
        rendered.set(section, key, str(value))
    stream = StringIO()
    stream.write("; Generated by scripts/generate_hbm_sensitivity_configs.py.\n")
    stream.write(f"; profile_id = {profile['profile_id']}\n")
    stream.write(f"; axis = {profile['axis']}\n")
    stream.write(f"; direction = {profile['direction']}\n\n")
    rendered.write(stream, space_around_delimiters=True)
    return stream.getvalue()


def render_profiles(manifest_path: Path) -> dict[Path, str]:
    manifest = load_manifest(manifest_path)
    baseline_spec = manifest["baseline"]
    if not isinstance(baseline_spec, dict):
        raise ValueError("baseline must be an object")
    baseline = read_ini((ROOT / str(baseline_spec["path"])).resolve())
    outputs: dict[Path, str] = {}
    for raw_profile in manifest["profiles"]:  # type: ignore[index]
        profile = dict(raw_profile)
        output = (ROOT / str(profile["output"])).resolve()
        content = render_profile(baseline, profile)
        digest = hashlib.sha256(content.encode("ascii")).hexdigest()
        if digest != profile.get("sha256"):
            raise ValueError(
                f"generated sensitivity hash mismatch: {profile['profile_id']}"
            )
        outputs[output] = content
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = render_profiles(args.manifest.resolve())
    stale: list[Path] = []
    for path, content in outputs.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="ascii") != content:
                stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="ascii")
    if stale:
        for path in stale:
            print(f"STALE {path}", file=sys.stderr)
        return 1
    action = "verified" if args.check else "generated"
    print(f"PASS {action} {len(outputs)} HBM sensitivity configs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
